### ISSUE TITLE
regression with 7.0.0 when using magellan-mocha-plugin

### ISSUE THREAD

**Issue by chenchaoyi** [TestArmada/magellan#106]
magellan 6.1.1 works well with mocha plugin, when updated to 7.0.0, I got error:
```
Fatal internal error while running a test: TypeError: Cannot read property 'stdout' of undefined
TypeError: Cannot read property 'stdout' of undefined
    at Reporter.listenTo (automation/node_modules/testarmada-magellan/src/reporters/stdout/reporter.js:21:13)
    at automation/node_modules/testarmada-magellan/src/test_runner.js:257:20
    at Array.forEach (native)
    at Object.TestRunner.spawnTestProcess (automation/node_modules/testarmada-magellan/src/test_runner.js:255:22)
    at Object.<anonymous> (automation/node_modules/testarmada-magellan/src/test_runner.js:455:14)
    at Timer.listOnTimeout (timers.js:92:15)`
```

**Comment by Maciek416** [comment]
Thanks for catching this! Working on a fix!
