### ISSUE TITLE
Parallel run fails with TypeError: undefined is not a function

### ISSUE THREAD

**Issue by asunar** [TestArmada/magellan#2]
To be able to run firefox tests updated configuration to use selenium driver 2.46.0 like this:
"server_path": "./node_modules/testarmada-magellan-nightwatch/node_modules/selenium-server/lib/runner/selenium-server-standalone-2.46.0.jar"

Chrome only => all tests pass
Firefox only => walmart-shirt.js fails, the rest pass.

Chrome,Firefox parallel fails with the following error:

λ "./node_modules/.bin/magellan" --browser=chrome,firefox --bail_fast
...
(1 / 3) <-- Worker 1 FAIL  tests/github.js @chrome,firefox
(2 / 3) <-- Worker 3 FAIL  tests/walmart-shirt.js @chrome,firefox
(3 / 3) <-- Worker 2 FAIL  tests/walmart-book.js @chrome,firefox
...
 nightwatch-magellan has found nightwatch configuration at  C:\Users\ASunar\boilerplate\temp\build-magellan-13e9e9364_24ccb1041__temp_assets\nightwatch.json
 chrome   TypeError: undefined is not a function
    at emitStartedTest (C:\Users\ASunar\boilerplate\node_modules\testarmada-magellan-nightwatch\lib\base-test-class.js:70:13)
    at Object.MagellanBaseTest.beforeEach (C:\Users\ASunar\boilerplate\node_modules\testarmada-magellan-nightwatch\lib\base-test-class.js:144:7)
    at TestSuite.<anonymous> (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:90:18)
    at TestSuite.makePromise (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:384:8)
    at Object.beforeEach (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:88:21)
    at TestSuite.beforeEach (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:323:21)
    at TestCase.run (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testcase.js:47:6)
    at TestSuite.runTestCase (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:284:20)
    at TestSuite.runNextTestCase (C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:272:21)
    at C:\Users\ASunar\boilerplate\node_modules\nightwatch\lib\runner\testsuite.js:220:19

http://www.screencast.com/t/H9Z0SguP

**Comment by Maciek416** [comment]
@asunar thanks for this -- taking a look

**Comment by Maciek416** [comment]
Thanks for reporting! The above error happens because we were treating `--browser` and `--browsers` differently. I've fixed it so that you can supply a list or a single browser to both and Magellan will accept either form.

Try magellan `1.5.18`, now published to npm (boilerplate project updated also).
