### ISSUE TITLE
Support for nightwatch.config.js instead of .json

### ISSUE THREAD

**Issue by hutber** [TestArmada/magellan#251]
Currently i house my nightwatch config in a js file `nightwatch.conf.js` so I am able to pass `env`'s into it. 

It would be great to have support in magellan

*Error*
```
hutber@hutber-blade /var/www/frontend $ npm run nightwatch

> shipamax@1.0.0 nightwatch /var/www/frontend
> DPRO=local ./node_modules/.bin/magellan --local_browser chrome -e

[INFO] [Magellan] Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /var/www/frontend/magellan.json
[INFO] [Magellan] Magellan is creating temporary files at: /var/www/frontend/temp
[INFO] [Magellan] Magellan 10.1.1
[INFO] [Magellan] Loaded test framework: 
[INFO] [Magellan]   testarmada-magellan-nightwatch-plugin
[INFO] [Magellan] Loaded test executors: 
[INFO] [Magellan]   testarmada-magellan-local-executor
[INFO] [Magellan] Enabled bail strategy: 
[INFO] [Magellan]   testarmada-magellan-never-bail-strategy: Magellan never bails, all tests will be executed at least once
/var/www/frontend/node_modules/testarmada-magellan-nightwatch-plugin/lib/get_tests.js:24
    throw new Error("Magellan-nightwatch test iterator cannot read nightwatch configuration: " + err.toString());
    ^

Error: Magellan-nightwatch test iterator cannot read nightwatch configuration: Error: Cannot find module '/var/www/frontend/conf/nightwatch.json'
    at module.exports (/var/www/frontend/node_modules/testarmada-magellan-nightwatch-plugin/lib/get_tests.js:24:11)
    at Object.module.exports [as getTests] (/var/www/frontend/node_modules/testarmada-magellan/src/get_tests.js:14:20)
    at module.exports (/var/www/frontend/node_modules/testarmada-magellan/src/cli.js:372:25)
    at Object.<anonymous> (/var/www/frontend/node_modules/testarmada-magellan/bin/magellan:23:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shipamax@1.0.0 nightwatch: `DPRO=local ./node_modules/.bin/magellan --local_browser chrome -e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shipamax@1.0.0 nightwatch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hutber/.npm/_logs/2018-02-08T16_17_30_480Z-debug.log

```

**Comment by archlichking** [comment]
Sorry for the late reply @hutber. Good news is we're working on it. Release ETA will be next week. Related ticket https://github.com/TestArmada/magellan-nightwatch-plugin/issues/17. PR https://github.com/TestArmada/magellan-nightwatch-plugin/pull/29

**Comment by archlichking** [comment]
testarmada-nightwatch-extra@5.1.0 and testarmada-magellan-nightwatch-plugin@8.0.0 are out to support this. Please follow https://github.com/TestArmada/magellan-nightwatch-plugin#800
