### ISSUE TITLE
Does not support win32 or win64? 

### ISSUE THREAD

**Issue by Mad-Mack** [TestArmada/magellan#265]
Does magellan support windows OS? I tried installing it to my local project and also cloned the git example given at the documentation.  It runs the sample tests in the example nightwatch project but still gets this error. 

[INFO] [Magellan] ============= Suite Complete =============
[INFO] [Magellan]      Status: PASSED
[INFO] [Magellan]     Runtime: 19.8s
[INFO] [Magellan] Total tests: 4
[INFO] [Magellan]  Successful: 4 / 4
[WARN] [Magellan] executor teardownRunner error: Error: Operation unsupported on Windows
(node:17160) UnhandledPromiseRejectionWarning: Error: Operation unsupported on Windows
    at getTree (C:\nw-magellan\boilerplate-nightwatch\node_modules\testarmada-tree-kill\index.js:141:13)
    at checkForZombies (C:\nw-magellan\boilerplate-nightwatch\node_modules\testarmada-tree-kill\index.js:21:16)
    at Object.getZombieChildren (C:\nw-magellan\boilerplate-nightwatch\node_modules\testarmada-tree-kill\index.js:85:3)
    at Object.module.exports [as processCleanup] (C:\nw-magellan\boilerplate-nightwatch\node_modules\testarmada-magellan\src\util\process_cleanup.js:23:20)
    at Promise.all.then.catch (C:\nw-magellan\boilerplate-nightwatch\node_modules\testarmada-magellan\src\cli.js:443:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

PC Specs:
Processor: Intel(R) Core(TM) i7-7600U CPU @2.80GHz 2.90GHz
System type: 64-bit Operating System, x64-based processor

**Comment by jboutin** [comment]
Also having this issue.


> Happening on both Windows 7 x64, and Windows 10 x64.
> -----
> **node**: v10.15.3
> **npm**: v5.3.0
> **yarn**: v1.15.2
> **testarmada-bloop**: v0.0.4,
> **testarmada-magellan**: v^10.1.0,
> **testarmada-magellan-browserstack-executor**: v^1.0.0-beta4,
> **testarmada-magellan-local-executor**: v^2.0.0,
> **testarmada-magellan-nightwatch-plugin**: v^7.0.0,
> **testarmada-magellan-saucelabs-executor**: v^5.0.0,
> **testarmada-nightwatch-extra**: v^5.0.0,

Any help with this, would be greatly appreciated.
