### ISSUE TITLE
TestArmada on integration

### ISSUE THREAD

**Issue by wadjson** [TestArmada/magellan#94]
Hey guys,

I have migrated my nightwatch project to using TestArmada and all works locally but I am unable to have the run against this integration environment 
 I am using something like this where 
 ./node_modules/testarmada-magellan/bin/magellan  --config=testenv.json --serial --browser=chrome --test=test/tests/login.e2e.js

**Comment by geekdave** [comment]
Hi @wadjson and welcome aboard!  Debugging remotely is tough, but we'll do our best to help.  Could you please help us by providing more info about your problem?  When you say you're "unable" what does that mean exactly?  Could you paste specific errors, and if possible the contents of your config and test files?  Thanks!

**Comment by wadjson** [comment]
Thank you for getting back:
 1.So basically, I am able to run the migrated tests locally using:
./node_modules/testarmada-magellan/bin/magellan --serial --browser=chrome --test=test/tests/login.e2e.js
2. To run this same test against  my integration environment  without magellan and just NIghtwatch, I use
nightwatch -c appletestenv.json -t test/tests/login.e2e.js
3. Now, my issue arises when I try to run the migrated tests against my integration environment .

**Comment by wadjson** [comment]
(Continue)
I have tried using 
 ./node_modules/testarmada-magellan/bin/magellan  --config=config- appletestenv.json --serial --browser=chrome --test=test/tests/login.e2e.js

**Comment by wadjson** [comment]
At this point, the test executes, but the e2e is being recorded on my local, and not on the integration box
(Sorry having this replies all over the place)

**Comment by wadjson** [comment]
./node_modules/testarmada-magellan/bin/magellan  --nightwatch_config=cherrytestenv.json --serial --browser=chrome --test=test/tests/login.e2e.js

Running:  Invalid login attempt should keep the user on the log in page
✖ TypeError: this.setElValue is not a function
    at Object.commands.fillUsername (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:53:18)
    at Object.commands.loginWithInvalidCredentials (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:114:18)
    at Object.module.exports.Invalid login attempt should keep the user on the log in page (/Users/dodzikossi/git/nuix-cherry/ui/test/tests/login.e2e.js:16:35)
    at Module.call (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:796:13)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:556:49
    at runSingle (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:137:13)
    at flush (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3

FAILED:  1 assertions failed (18ms)

Running:  Global message should show count for duplicate messages
✖ TypeError: this.clickEl is not a function
    at Object.commands.clickLoginButton (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:82:18)
    at Object.module.exports.Global message should show count for duplicate messages (/Users/dodzikossi/git/nuix-cherry/ui/test/tests/login.e2e.js:29:19)
    at Module.call (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:796:13)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:556:49
    at runSingle (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:137:13)
    at flush (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)


Error retrieving a new session from the selenium server
Error: connect ECONNREFUSED 10.32.0.228:12001
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)


Connection refused! Is selenium server started?



============= Suite Complete =============

     Status: FAILED
    Runtime: 5s
Total tests: 1
 Successful: 0 / 1
     Failed: 1 / 1

**Comment by wadjson** [comment]
ENV=cherry-int.nuix-philly.com ./node_modules/testarmada-magellan/bin/magellan  --nightwatch_config=cherrytestenv.json --serial --browser=chrome --test=test/tests/login.e2e.js

Running:  Invalid login attempt should keep the user on the log in page
✖ TypeError: this.setElValue is not a function
    at Object.commands.fillUsername (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:53:18)
    at Object.commands.loginWithInvalidCredentials (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:114:18)
    at Object.module.exports.Invalid login attempt should keep the user on the log in page (/Users/dodzikossi/git/nuix-cherry/ui/test/tests/login.e2e.js:16:35)
    at Module.call (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:796:13)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:556:49
    at runSingle (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:137:13)
    at flush (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3

FAILED:  1 assertions failed (20ms)

Running:  Global message should show count for duplicate messages
✖ TypeError: this.clickEl is not a function
    at Object.commands.clickLoginButton (/Users/dodzikossi/git/nuix-cherry/ui/test/pages/login-page.js:82:18)
    at Object.module.exports.Global message should show count for duplicate messages (/Users/dodzikossi/git/nuix-cherry/ui/test/tests/login.e2e.js:29:19)
    at Module.call (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:796:13)
    at /Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:556:49
    at runSingle (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:137:13)
    at flush (/Users/dodzikossi/git/nuix-cherry/ui/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

FAILED:  1 assertions failed (10ms)

Running:  User only has access to the login page if they are not logged in


Error retrieving a new session from the selenium server
Error: connect ECONNREFUSED 10.32.0.228:12001
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)


Connection refused! Is selenium server started?



============= Suite Complete =============

     Status: FAILED
    Runtime: 5.4s
Total tests: 1
 Successful: 0 / 1
     Failed: 1 / 1

**Comment by geekdave** [comment]
Looks like you may be missing a dependency in your package.json.

` this.clickEl is not a function`

This function is defined in https://github.com/TestArmada/magellan-nightwatch, and published as the npm module `testarmada-magellan-nightwatch`

Is it possible that you installed this in your dev environment but not your integration env?

**Comment by wadjson** [comment]
Hey Dave,
That was correct.. I updated my integration env with these and I no longer get this.clickEl is not a function error.

"custom_commands_path" : [
    "test/custom-commands",
    "node_modules/testarmada-magellan-nightwatch/lib/commands"
    ],
  "custom_assertions_path" : [
    "test/custom-assertions",
    "node_modules/testarmada-magellan-nightwatch/lib/assertions"
    ],

I do now get a diff error related to selenium server

Error retrieving a new session from the selenium server
Error: connect ECONNREFUSED 10.32.0.228:12001
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)


Connection refused! Is selenium server started?



============= Suite Complete =============

     Status: FAILED
    Runtime: 5s
Total tests: 1
 Successful: 0 / 1
     Failed: 1 / 1

**Comment by wadjson** [comment]
Hey Dave,
My colleague here @ work was able to get pass the selenium port issue by updating magellan.json

{
  "max_test_attempts": 2,
  "max_workers": 1,
  "base_port_start": 4443,
  "base_port_range": 1,
  "base_port_spacing": 0
}

Thanks for the help
